if (!isServer || {isRemoteExecuted && {isNil "_CSR_requestContext"}}) exitWith {[false,"Server-local API only.",[]]};
params [["_args",[],[[]]],["_actor","server",[""]]];
if (localNamespace getVariable ["CSR_readOnly",true]) exitWith {[false,"Storage is read-only.",[]]};
if (count _args != 6) exitWith {[false,"Invalid personnel arguments.",[]]};
_args params ["_uid","_name","_rank","_eligible","_rev","_regRev"];
if !(_uid isEqualType "" && {_name isEqualType ""} && {_rank isEqualType ""} && {_eligible isEqualType []} && {_rev isEqualType 0} && {_regRev isEqualType 0}) exitWith {[false,"Invalid personnel fields.",[]]};
if (count _uid != 17 || {(toArray _uid) findIf {_x < 48 || {_x > 57}} >= 0}) exitWith {[false,"Steam UID must contain 17 digits.",[]]};
if (([_name] call CSR_fnc_divisionName) == "") exitWith {[false,"Name must contain 1-64 printable characters.",[]]};
private _rankData = [_rank] call CSR_fnc_resolveRank;
if (_rankData isEqualTo []) exitWith {[false,"Select an approved rank.",[]]};
private _r = call CSR_fnc_getRegistry;
if (_regRev != (_r # 0)) exitWith {[false,"Divisions changed. Reload before saving.",[]]};
private _ids = (_r # 3) apply {_x # 0};
if (_eligible findIf {!(_x isEqualType "") || {!(_x in _ids)}} >= 0) exitWith {[false,"Unknown eligible division.",[]]};
_eligible = +_eligible;
_eligible pushBackUnique (_r # 1);
_eligible = _eligible arrayIntersect _eligible;
private _roster = localNamespace getVariable "CSR_roster";
private _members = localNamespace getVariable "CSR_members";
private _old = +(_roster getOrDefault [_uid,[]]);
private _expected = if (_old isEqualTo []) then {-1} else {_old # 10};
if (_expected != _rev) exitWith {[false,"Record changed. Reload before saving.",[]]};
private _oldMember = +(_members getOrDefault [_uid,[_uid,[_r # 1],_r # 1]]);
private _row = if (_old isEqualTo []) then {[_uid,_name,_rankData # 1,"Unassigned",(call CSR_fnc_getDivisions) # 1,0,0,0,0,0,0,[]]} else {+_old};
_row set [1,_name]; _row set [2,_rankData # 1]; _row set [10,_expected+1];
_roster set [_uid,_row];
_members set [_uid,[_uid,_eligible,_oldMember # 2]];
[_actor,_uid,[_old,_oldMember],[_row,[_uid,_eligible,_oldMember # 2]]] call CSR_fnc_audit;
call CSR_fnc_persist;
{if (getPlayerUID _x == _uid) then {[_x,_uid] call CSR_fnc_syncRank;};} forEach (allPlayers - entities "HeadlessClient_F");
["CSR_rosterChanged",[_uid,+_row,_actor]] call CBA_fnc_localEvent;
["CSR_eligibilityChanged",[_uid,+_eligible,_actor]] call CBA_fnc_localEvent;
[true,"Personnel and eligibility saved.",+_row]
